require('dotenv').config()

const {
    MONGO_DEV_CONNECTION_STRING,
    MONGO_TEST_CONNECTION_STRING,
    MONGO_PRODUCTION_CONNECTION_STRING,
    NODE_ENV
} = process.env

module.exports = {
    MONGO_DEV_CONNECTION_STRING,
    MONGO_TEST_CONNECTION_STRING,
    MONGO_PRODUCTION_CONNECTION_STRING,
    NODE_ENV
}
